// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: live.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 总的消息体
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType string `protobuf:"bytes,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 接收弹幕消息内容请求
type WebClientSendBarrageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Type  string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WebClientSendBarrageReq) Reset() {
	*x = WebClientSendBarrageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebClientSendBarrageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebClientSendBarrageReq) ProtoMessage() {}

func (x *WebClientSendBarrageReq) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebClientSendBarrageReq.ProtoReflect.Descriptor instead.
func (*WebClientSendBarrageReq) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{1}
}

func (x *WebClientSendBarrageReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WebClientSendBarrageReq) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *WebClientSendBarrageReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 客户端弹幕消息内容响应
type WebClientSendBarrageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgId    float32 `protobuf:"fixed32,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	UserId   float32 `protobuf:"fixed32,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string  `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Avatar   string  `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Text     string  `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Color    string  `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Type     string  `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *WebClientSendBarrageRes) Reset() {
	*x = WebClientSendBarrageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebClientSendBarrageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebClientSendBarrageRes) ProtoMessage() {}

func (x *WebClientSendBarrageRes) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebClientSendBarrageRes.ProtoReflect.Descriptor instead.
func (*WebClientSendBarrageRes) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{2}
}

func (x *WebClientSendBarrageRes) GetMsgId() float32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *WebClientSendBarrageRes) GetUserId() float32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebClientSendBarrageRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WebClientSendBarrageRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *WebClientSendBarrageRes) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WebClientSendBarrageRes) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *WebClientSendBarrageRes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 客户端弹幕消息内容响应
type WebClientHistoricalBarrageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*WebClientSendBarrageRes `protobuf:"bytes,1,rep,name=chatList,proto3" json:"chatList,omitempty"`
}

func (x *WebClientHistoricalBarrageRes) Reset() {
	*x = WebClientHistoricalBarrageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebClientHistoricalBarrageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebClientHistoricalBarrageRes) ProtoMessage() {}

func (x *WebClientHistoricalBarrageRes) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebClientHistoricalBarrageRes.ProtoReflect.Descriptor instead.
func (*WebClientHistoricalBarrageRes) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{3}
}

func (x *WebClientHistoricalBarrageRes) GetList() []*WebClientSendBarrageRes {
	if x != nil {
		return x.List
	}
	return nil
}

type EnterLiveRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   float32 `protobuf:"fixed32,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string  `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar   string  `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *EnterLiveRoom) Reset() {
	*x = EnterLiveRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterLiveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterLiveRoom) ProtoMessage() {}

func (x *EnterLiveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterLiveRoom.ProtoReflect.Descriptor instead.
func (*EnterLiveRoom) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{4}
}

func (x *EnterLiveRoom) GetUserId() float32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnterLiveRoom) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EnterLiveRoom) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 客户端在线人数
type WebClientEnterLiveRoomRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   float32          `protobuf:"fixed32,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username string           `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar   string           `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Type     bool             `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	List     []*EnterLiveRoom `protobuf:"bytes,5,rep,name=chatList,proto3" json:"chatList,omitempty"`
}

func (x *WebClientEnterLiveRoomRes) Reset() {
	*x = WebClientEnterLiveRoomRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_live_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebClientEnterLiveRoomRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebClientEnterLiveRoomRes) ProtoMessage() {}

func (x *WebClientEnterLiveRoomRes) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebClientEnterLiveRoomRes.ProtoReflect.Descriptor instead.
func (*WebClientEnterLiveRoomRes) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{5}
}

func (x *WebClientEnterLiveRoomRes) GetUserId() float32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WebClientEnterLiveRoomRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WebClientEnterLiveRoomRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *WebClientEnterLiveRoomRes) GetType() bool {
	if x != nil {
		return x.Type
	}
	return false
}

func (x *WebClientEnterLiveRoomRes) GetList() []*EnterLiveRoom {
	if x != nil {
		return x.List
	}
	return nil
}

var File_live_proto protoreflect.FileDescriptor

var file_live_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x61,
	0x72, 0x72, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x57,
	0x0a, 0x17, 0x57, 0x65, 0x62, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x61, 0x72, 0x72, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x72, 0x72, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x55, 0x0a, 0x1d, 0x57, 0x65, 0x62, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x42, 0x61, 0x72, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x61, 0x72, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x57,
	0x65, 0x62, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x72, 0x72,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x0d,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0xa8, 0x01, 0x0a, 0x19, 0x57,
	0x65, 0x62, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76,
	0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x72, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_live_proto_rawDescOnce sync.Once
	file_live_proto_rawDescData = file_live_proto_rawDesc
)

func file_live_proto_rawDescGZIP() []byte {
	file_live_proto_rawDescOnce.Do(func() {
		file_live_proto_rawDescData = protoimpl.X.CompressGZIP(file_live_proto_rawDescData)
	})
	return file_live_proto_rawDescData
}

var file_live_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_live_proto_goTypes = []interface{}{
	(*Message)(nil),                       // 0: barrage.Message
	(*WebClientSendBarrageReq)(nil),       // 1: barrage.WebClientSendBarrageReq
	(*WebClientSendBarrageRes)(nil),       // 2: barrage.WebClientSendBarrageRes
	(*WebClientHistoricalBarrageRes)(nil), // 3: barrage.WebClientHistoricalBarrageRes
	(*EnterLiveRoom)(nil),                 // 4: barrage.EnterLiveRoom
	(*WebClientEnterLiveRoomRes)(nil),     // 5: barrage.WebClientEnterLiveRoomRes
}
var file_live_proto_depIdxs = []int32{
	2, // 0: barrage.WebClientHistoricalBarrageRes.chatList:type_name -> barrage.WebClientSendBarrageRes
	4, // 1: barrage.WebClientEnterLiveRoomRes.chatList:type_name -> barrage.EnterLiveRoom
	2, // [2:2] is the sub-chatList for method output_type
	2, // [2:2] is the sub-chatList for method input_type
	2, // [2:2] is the sub-chatList for extension type_name
	2, // [2:2] is the sub-chatList for extension extendee
	0, // [0:2] is the sub-chatList for field type_name
}

func init() { file_live_proto_init() }
func file_live_proto_init() {
	if File_live_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_live_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebClientSendBarrageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebClientSendBarrageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebClientHistoricalBarrageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterLiveRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_live_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebClientEnterLiveRoomRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_live_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_live_proto_goTypes,
		DependencyIndexes: file_live_proto_depIdxs,
		MessageInfos:      file_live_proto_msgTypes,
	}.Build()
	File_live_proto = out.File
	file_live_proto_rawDesc = nil
	file_live_proto_goTypes = nil
	file_live_proto_depIdxs = nil
}
